# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-json
        exclude: ampel/contrib/hu/test
    -   id: check-yaml
    -   id: pretty-format-json
        args: [--no-sort-keys, --autofix, --indent=2]
        exclude: ampel/contrib/hu/test
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports]
-   repo: https://github.com/PyCQA/isort
    rev: 5.4.2
    hooks:
    -   id: isort
        # use a multi-line indent style that isort and black can agree on
        args: [--fass, --multi-line=VERTICAL_HANGING_INDENT, --trailing-comma]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
fail_fast: true
